name: "PR Title Checker"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ github.token }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-check-config.json"
